#!/bin/bash
# THE BEER-WARE LICENSE:
# <leokewitz@gmail.com> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.
# Leonardo Kewitz

# Color codes
red='\033[0;31m'
yellow='\033[0;33m'
blue='\033[0;34m'
NC='\033[0m' # No colors


if ! [[ $(cat $1) =~ ^(chore|docs|feat|fix|refactor|style|test): ]]; then
  printf "${red}Please use semantic commit messages:\n"
  printf "${yellow}feat: ${blue}add hat wobble\n"
  printf "${yellow}^--^${blue}  ^------------^ ]-> Summary in present tense.${yellow}\n"
  printf "|\n"
  printf "+---> Type: chore, docs, feat, fix, refactor, style, or test.\n${NC}"
  exit 1
fi
